### ISSUE TITLE
KeyError: 'comment_count'

### ISSUE THREAD

**Issue by bdosono** [davidemdot/FacebookGroupScraper#1]
Received following KeyError for 'comment_count'
<img width="531" alt="screen shot 2016-11-02 at 1 30 30 pm" src="https://cloud.githubusercontent.com/assets/3020597/19939818/da848c44-a100-11e6-82d2-3c25bb378e56.png">

**Comment by davidemdot** [comment]
Thanks, @bdosono, and sorry for the delay. I think this issue is solved now.

**Comment by bdosono** [comment]
Thank you, @davidemdot! Yes, the code now compiles without error on my side.
