### ISSUE TITLE
KeyError 'link' & getting user_group token

### ISSUE THREAD

**Issue by yarnball** [davidemdot/FacebookGroupScraper#2]
Hi,

I have been able to get the "user_group" token. It was a bit of a work-around.

1. Go to Facebook API explorer
2. On the right "dropdown" click **Get Access Token**
3. Change the version to 2.2
4. Select "user_group"

It runs, but then I get the error "KeyError : Link". Im trying to scrape from a group page

```
(23:59:46) 100 threads and 618 comments processed
Traceback (most recent call last):
  File "fb_group_scraper.py", line 231, in <module>
    main()
  File "fb_group_scraper.py", line 214, in main
    num_threads, num_comments = write_csv()
  File "fb_group_scraper.py", line 188, in write_csv
    output.writerow(process_post(thread))
  File "fb_group_scraper.py", line 93, in process_post
    link = format_string(post['name'] + ': ' + post['link'])
KeyError: 'link'
```

**Comment by davidemdot** [comment]
Thanks for reporting the issue, @yarnball. Please try again. I think it's solved now.
