### ISSUE TITLE
Script Connection breaks or timeout

### ISSUE THREAD

**Issue by luckyankit** [davidemdot/FacebookGroupScraper#3]
Hi,

Thanks for building this wonderful script. Although the script works great, I had trouble making it run on few groups which has lots of engagements like lots of posts and comments on it. 

Sometimes it doesn't show any error and the command ends without showing any progress. Happens when suppose there are like 4K comments in 50 threads, so the script doesn't work. To make it work, I change the limit to 10 or 50 which is by default 100 in the get_group_data function. 

But still this method breaks after downloading few hundred's threads. I don't know why that happens. Is there any way to increase the timeout of the script or some idea you may could suggest?

**Comment by davidemdot** [comment]
First of all, thanks for your comment. I only tried this script on groups with an average number of threads and comments, but I've realize now that it fails when it has to deal with bigger groups. Please let me have a look these days and I'll say you something about it.

**Comment by luckyankit** [comment]
Glad to get your attention here. Please take care of one more point i.e. sometimes the script skipped an whole year posts while fetching. Once there was a case, where it alternatively skipped years posts like the csv had 2016, 2015, 2014, skipped 2013, 2012, skipped 2011, 2010 and then it broke...

**Comment by luckyankit** [comment]
Facing one more error - UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)

**Comment by davidemdot** [comment]
I think it has to work now. If you still detect any error, please tell me what group ID you're using to check it.

**Comment by luckyankit** [comment]
Thanks gonna try it out. One thing I forgot to ask, like if it possible to add "auto retry from same location" option if remote host doesn't respond. That'll be highly helpful in cases of old groups.

**Comment by luckyankit** [comment]
Scripts seem to be working great now & auto retrying also working well. One last thing where I would like to get your attention is.. sometimes in many groups, scripts stop saying that's all **X threads and X comments processed**. However, that is not true at many times. Suppose if any group has 18K posts, It might break randomly at any number saying that's all it have. 

Upon retrying sometimes it does exceed previous number, sometimes breaks at less count. I think at some points script is not able to detect Previous and Next link, hence it breaks in b/w reporting that's all it have. Any solution for that. 

And thanks a lot for all the modifications you did here.

**Comment by davidemdot** [comment]
Well, it seems that Facebook doesn't like massive queries from a specific source ;-).
Although I've been running tests in busy groups and I haven't noticed anything. Could you give me a particular group ID where it happens? I'd like to have a look.

**Comment by luckyankit** [comment]
not able to reproduce that error anymore.. so I think that is solved now... 

Also, is there any way that the script may resume after it may face any internet downtime issue? 

Thanks for all the help you're doing. I'll also email you for a custom modification on the script. Hoping I could get your interest on it.

**Comment by davidemdot** [comment]
Yes, the script resumes automatically when the Internet connection goes back :-).
