### ISSUE TITLE
Getting Error:  Keyerror: 'name'

### ISSUE THREAD

**Issue by akkiverma** [davidemdot/FacebookGroupScraper#4]
While running the script in one of the group, it gave me this error many times, 

File "fb_group_scraper.py", line 81, in process_post
  author = format_string(post['from']['name']
KeyError: 'name'

**Comment by davidemdot** [comment]
I hope now it's working right!

**Comment by luckyankit** [comment]
I guess Yes that's fixed... Thanks a lot.. but facing another:

File "fb_group_scraper.py", line 65, in format_string
 0xD: 0x20

TypeError: expected a string or other character buffer object

**Comment by luckyankit** [comment]
and I forgot to tell you one thing... I do modify your file for utf-8 support. Here are the changes:

At the top:

```
import csv
import datetime
import json
import time
import urllib2
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```

At ```
def format_string(text)
    """Format a string in a good way.
    """
    if text is None:
        return ''

    return ' '.join(
        text.translate({
            0x2018: 0x27,
            0x2019: 0x27,
            0x201C: 0x22,
            0x201D: 0x22,
            0xA0: 0x20,
            0xA: 0x20,
            0xD: 0x20
        }).**decode**('utf-8').split())
```

Changed `encode` to `decode`

**Comment by davidemdot** [comment]
D'oh! It was a stupid mistake. It has to be solved now. Please try again.

**Comment by luckyankit** [comment]
Thanks man :)

And adding those lines above for utf-8 support are of any use or not? or those are just bluffing me :D

**Comment by luckyankit** [comment]
Indeed that string format error is gone. But the script still doesn't resume upon internet interruption. This error comes up:

  if err.code == 400:
AttributeError: 'URLError' object has no attribute 'code'

I guess this should be the last error in it 😄

**Comment by davidemdot** [comment]
Definitely not my best week. There is a new version ready for test.

By the way, I don't understand the point of change `encode` to `decode`. I think this way can avoid errors writing the CSV file.

**Comment by luckyankit** [comment]
Yeah at one point I had some trouble related to ascii characters something, not able to recall exactly. So I googled the solution and found these lines to add. After I made these changes, ascii error didn't came.

**Comment by luckyankit** [comment]
checked the script, yeah attribute error is gone and script is resuming upon internet connect. Great great 👍

**Comment by luckyankit** [comment]
One more error:

line 85, in process_post
    likes = post['likes']['summary']['total_count']
KeyError: 'likes'

hahahahaha...

**Comment by davidemdot** [comment]
It's so unpleasant. Facebook API doesn't document properly in which cases a specific field won't be present in its response. Let me assure I check every field every single time.

Thanks again for your feedback, mate.

**Comment by davidemdot** [comment]
By the way, I'm testing every version before upload it and only notice you when it seems to be working fine.
If you get any error again, please tell me the group ID you're scraping. I don't like to waste your time.

**Comment by akkiverma** [comment]
One more :)

File "fb_group_scraper.py", line 78, in process_post
author = format_string(post('from'].get('name'))
KeyError: 'from'

**Comment by davidemdot** [comment]
Yup, I forgot that field. Please check it now!

;-)

**Comment by akkiverma** [comment]
I guess I missed the previous email. Thanks for fixing this, but I haven't tried it yet. But I am sure it'll work fine. I hope with all the feedback, you have just perfected the script :)

**Comment by davidemdot** [comment]
Sure! Thanks so much, Ankit!

**Comment by akkiverma** [comment]
Any chance to get the Image urls in status and comments 

and link url in link posts?

**Comment by akkiverma** [comment]
Also please, add auto resume feature upon receiving following error:

socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host.

**Comment by davidemdot** [comment]
That kind of information is normally part of "message" field, between brackets. I know sometimes it doesn't work properly, but only when Facebook API doesn't return the related link. Anyway, I'll check it again carefully in the future, and I'll try to handle socket errors like that one.

**Comment by akkiverma** [comment]
That occurs only when Internet is troublesome :)

But is it possible to get image urls? Please add that option.. shall be super-useful.

**Comment by davidemdot** [comment]
I'll improve it as soon as I can. Meanwhile, try adding this code...
```
            url = format_string(post['attachment'].get('url'))
            if url != '':
                if message != '':
                    message += ' '
                message += '[' + url + ']'
```
... after:
```
        if 'attachment' in post:
            kind += '_' + format_string(post['attachment'].get('type'))
```

**Comment by akkiverma** [comment]
Thanks a lot.. Shall gonna try right away..

**Comment by akkiverma** [comment]
Tried.. didn't worked.. throwed the error:

IndentationError: unexpected indent at line  url = format_string(post['attachment'].get('url'))

**Comment by davidemdot** [comment]
Please check this page: http://www.diveintopython.net/getting_to_know_python/indenting_code.html

;-)

**Comment by akkiverma** [comment]
Cannot understood.. not a programmer here :(
