### ISSUE TITLE
Only working when being admin

### ISSUE THREAD

**Issue by philwall3** [davidemdot/FacebookGroupScraper#6]
Hi,
thanks for providing that awesome script!
It works great on groups where I'm admin, but on groups where I'm just a member it gives me a "That's all! 0 threads and 0 comments in total". Your description states that it also works as a member. 
Did Facebook change something or am I doing something wrong?

Thanks!

**Comment by davidemdot** [comment]
Hi @philwall3,

I have just realized that the version 2.3 of the Facebook API is no longer available. Last few versions doesn't allow to get data from those groups in which you are not admin.

So sorry.

:-(

**Comment by philwall3** [comment]
Aww that's sad. :(
But no need to be sorry, there is nothing we can do if Facebook screws us over...
